// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: multisigwallet/member_transaction.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MemberTransaction struct {
	Index      string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	WalletName string `protobuf:"bytes,2,opt,name=walletName,proto3" json:"walletName,omitempty"`
	Member     string `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"`
	Action     string `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	State      string `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Signers    string `protobuf:"bytes,6,opt,name=signers,proto3" json:"signers,omitempty"`
}

func (m *MemberTransaction) Reset()         { *m = MemberTransaction{} }
func (m *MemberTransaction) String() string { return proto.CompactTextString(m) }
func (*MemberTransaction) ProtoMessage()    {}
func (*MemberTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_c67d93c1673263d6, []int{0}
}
func (m *MemberTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MemberTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MemberTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MemberTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberTransaction.Merge(m, src)
}
func (m *MemberTransaction) XXX_Size() int {
	return m.Size()
}
func (m *MemberTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_MemberTransaction proto.InternalMessageInfo

func (m *MemberTransaction) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *MemberTransaction) GetWalletName() string {
	if m != nil {
		return m.WalletName
	}
	return ""
}

func (m *MemberTransaction) GetMember() string {
	if m != nil {
		return m.Member
	}
	return ""
}

func (m *MemberTransaction) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *MemberTransaction) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *MemberTransaction) GetSigners() string {
	if m != nil {
		return m.Signers
	}
	return ""
}

func init() {
	proto.RegisterType((*MemberTransaction)(nil), "threefoldtech.threefoldhub.multisigwallet.MemberTransaction")
}

func init() {
	proto.RegisterFile("multisigwallet/member_transaction.proto", fileDescriptor_c67d93c1673263d6)
}

var fileDescriptor_c67d93c1673263d6 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xcf, 0x2d, 0xcd, 0x29,
	0xc9, 0x2c, 0xce, 0x4c, 0x2f, 0x4f, 0xcc, 0xc9, 0x49, 0x2d, 0xd1, 0xcf, 0x4d, 0xcd, 0x4d, 0x4a,
	0x2d, 0x8a, 0x2f, 0x29, 0x4a, 0xcc, 0x2b, 0x4e, 0x4c, 0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0xd2, 0x2c, 0xc9, 0x28, 0x4a, 0x4d, 0x4d, 0xcb, 0xcf, 0x49, 0x29, 0x49,
	0x4d, 0xce, 0xd0, 0x83, 0xf3, 0x32, 0x4a, 0x93, 0xf4, 0x50, 0xcd, 0x50, 0x5a, 0xc9, 0xc8, 0x25,
	0xe8, 0x0b, 0x36, 0x27, 0x04, 0x61, 0x8c, 0x90, 0x08, 0x17, 0x6b, 0x66, 0x5e, 0x4a, 0x6a, 0x85,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x84, 0x23, 0x24, 0xc7, 0xc5, 0x05, 0xd1, 0xe5, 0x97,
	0x98, 0x9b, 0x2a, 0xc1, 0x04, 0x96, 0x42, 0x12, 0x11, 0x12, 0xe3, 0x62, 0x83, 0x38, 0x49, 0x82,
	0x19, 0x2c, 0x07, 0xe5, 0x81, 0xc4, 0x21, 0xe6, 0x4a, 0xb0, 0x40, 0xc4, 0x11, 0xb6, 0x14, 0x97,
	0x24, 0x96, 0xa4, 0x4a, 0xb0, 0x42, 0x6c, 0x01, 0x73, 0x84, 0x24, 0xb8, 0xd8, 0x8b, 0x33, 0xd3,
	0xf3, 0x52, 0x8b, 0x8a, 0x25, 0xd8, 0xc0, 0xe2, 0x30, 0xae, 0x53, 0xf8, 0x89, 0x47, 0x72, 0x8c,
	0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7, 0x38, 0xe1, 0xb1, 0x1c, 0xc3, 0x85, 0xc7, 0x72,
	0x0c, 0x37, 0x1e, 0xcb, 0x31, 0x44, 0xd9, 0xa6, 0x67, 0x96, 0x80, 0x3c, 0x97, 0x9c, 0x9f, 0xab,
	0x8f, 0xe2, 0x77, 0x04, 0x2f, 0x3e, 0xa3, 0x34, 0x49, 0xbf, 0x42, 0x1f, 0x2d, 0x08, 0x4b, 0x2a,
	0x0b, 0x52, 0x8b, 0x93, 0xd8, 0xc0, 0xc1, 0x66, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xb4, 0xc2,
	0x5e, 0xa7, 0x61, 0x01, 0x00, 0x00,
}

func (m *MemberTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MemberTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MemberTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signers) > 0 {
		i -= len(m.Signers)
		copy(dAtA[i:], m.Signers)
		i = encodeVarintMemberTransaction(dAtA, i, uint64(len(m.Signers)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.State) > 0 {
		i -= len(m.State)
		copy(dAtA[i:], m.State)
		i = encodeVarintMemberTransaction(dAtA, i, uint64(len(m.State)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Action) > 0 {
		i -= len(m.Action)
		copy(dAtA[i:], m.Action)
		i = encodeVarintMemberTransaction(dAtA, i, uint64(len(m.Action)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Member) > 0 {
		i -= len(m.Member)
		copy(dAtA[i:], m.Member)
		i = encodeVarintMemberTransaction(dAtA, i, uint64(len(m.Member)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.WalletName) > 0 {
		i -= len(m.WalletName)
		copy(dAtA[i:], m.WalletName)
		i = encodeVarintMemberTransaction(dAtA, i, uint64(len(m.WalletName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintMemberTransaction(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMemberTransaction(dAtA []byte, offset int, v uint64) int {
	offset -= sovMemberTransaction(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MemberTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovMemberTransaction(uint64(l))
	}
	l = len(m.WalletName)
	if l > 0 {
		n += 1 + l + sovMemberTransaction(uint64(l))
	}
	l = len(m.Member)
	if l > 0 {
		n += 1 + l + sovMemberTransaction(uint64(l))
	}
	l = len(m.Action)
	if l > 0 {
		n += 1 + l + sovMemberTransaction(uint64(l))
	}
	l = len(m.State)
	if l > 0 {
		n += 1 + l + sovMemberTransaction(uint64(l))
	}
	l = len(m.Signers)
	if l > 0 {
		n += 1 + l + sovMemberTransaction(uint64(l))
	}
	return n
}

func sovMemberTransaction(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMemberTransaction(x uint64) (n int) {
	return sovMemberTransaction(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MemberTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMemberTransaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MemberTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MemberTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMemberTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMemberTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMemberTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WalletName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMemberTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMemberTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMemberTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WalletName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Member", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMemberTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMemberTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMemberTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Member = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Action", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMemberTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMemberTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMemberTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Action = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMemberTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMemberTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMemberTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.State = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMemberTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMemberTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMemberTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signers = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMemberTransaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMemberTransaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMemberTransaction(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMemberTransaction
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMemberTransaction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMemberTransaction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMemberTransaction
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMemberTransaction
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMemberTransaction
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMemberTransaction        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMemberTransaction          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMemberTransaction = fmt.Errorf("proto: unexpected end of group")
)
