// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: multisigwallet/next_member_transaction.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type NextMemberTransaction struct {
	IdValue uint64 `protobuf:"varint,1,opt,name=idValue,proto3" json:"idValue,omitempty"`
}

func (m *NextMemberTransaction) Reset()         { *m = NextMemberTransaction{} }
func (m *NextMemberTransaction) String() string { return proto.CompactTextString(m) }
func (*NextMemberTransaction) ProtoMessage()    {}
func (*NextMemberTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_53e1e3591f283105, []int{0}
}
func (m *NextMemberTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NextMemberTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NextMemberTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NextMemberTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NextMemberTransaction.Merge(m, src)
}
func (m *NextMemberTransaction) XXX_Size() int {
	return m.Size()
}
func (m *NextMemberTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_NextMemberTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_NextMemberTransaction proto.InternalMessageInfo

func (m *NextMemberTransaction) GetIdValue() uint64 {
	if m != nil {
		return m.IdValue
	}
	return 0
}

func init() {
	proto.RegisterType((*NextMemberTransaction)(nil), "threefoldtech.threefoldhub.multisigwallet.NextMemberTransaction")
}

func init() {
	proto.RegisterFile("multisigwallet/next_member_transaction.proto", fileDescriptor_53e1e3591f283105)
}

var fileDescriptor_53e1e3591f283105 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0xc9, 0x2d, 0xcd, 0x29,
	0xc9, 0x2c, 0xce, 0x4c, 0x2f, 0x4f, 0xcc, 0xc9, 0x49, 0x2d, 0xd1, 0xcf, 0x4b, 0xad, 0x28, 0x89,
	0xcf, 0x4d, 0xcd, 0x4d, 0x4a, 0x2d, 0x8a, 0x2f, 0x29, 0x4a, 0xcc, 0x2b, 0x4e, 0x4c, 0x2e, 0xc9,
	0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xd2, 0x2c, 0xc9, 0x28, 0x4a, 0x4d, 0x4d,
	0xcb, 0xcf, 0x49, 0x29, 0x49, 0x4d, 0xce, 0xd0, 0x83, 0xf3, 0x32, 0x4a, 0x93, 0xf4, 0x50, 0x0d,
	0x52, 0x32, 0xe4, 0x12, 0xf5, 0x4b, 0xad, 0x28, 0xf1, 0x05, 0x1b, 0x15, 0x82, 0x30, 0x49, 0x48,
	0x82, 0x8b, 0x3d, 0x33, 0x25, 0x2c, 0x31, 0xa7, 0x34, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x25,
	0x08, 0xc6, 0x75, 0x0a, 0x3f, 0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4,
	0x18, 0x27, 0x3c, 0x96, 0x63, 0xb8, 0xf0, 0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x86, 0x28, 0xdb,
	0xf4, 0xcc, 0x12, 0x90, 0x1d, 0xc9, 0xf9, 0xb9, 0xfa, 0x28, 0x4e, 0x40, 0xf0, 0xe2, 0x33, 0x4a,
	0x93, 0xf4, 0x2b, 0xf4, 0xd1, 0xbc, 0x53, 0x52, 0x59, 0x90, 0x5a, 0x9c, 0xc4, 0x06, 0x76, 0xbd,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x05, 0x02, 0xd7, 0x59, 0xed, 0x00, 0x00, 0x00,
}

func (m *NextMemberTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NextMemberTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NextMemberTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IdValue != 0 {
		i = encodeVarintNextMemberTransaction(dAtA, i, uint64(m.IdValue))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintNextMemberTransaction(dAtA []byte, offset int, v uint64) int {
	offset -= sovNextMemberTransaction(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NextMemberTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IdValue != 0 {
		n += 1 + sovNextMemberTransaction(uint64(m.IdValue))
	}
	return n
}

func sovNextMemberTransaction(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozNextMemberTransaction(x uint64) (n int) {
	return sovNextMemberTransaction(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NextMemberTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNextMemberTransaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NextMemberTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NextMemberTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IdValue", wireType)
			}
			m.IdValue = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNextMemberTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IdValue |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipNextMemberTransaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNextMemberTransaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNextMemberTransaction(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNextMemberTransaction
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNextMemberTransaction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNextMemberTransaction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNextMemberTransaction
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupNextMemberTransaction
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthNextMemberTransaction
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthNextMemberTransaction        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNextMemberTransaction          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupNextMemberTransaction = fmt.Errorf("proto: unexpected end of group")
)
