exec: |
  bash -c '
  while :
  do
    if threefold_hubd query account $(threefold_hubd keys show $KEYNAME  --keyring-backend test | grep -i address | cut -d ":" -f 2 ) &>/dev/null; then
      echo "Node is ready"
      break
    else
    echo "Node still syncing sleeping"
      sleep 60
    fi
  done
  VALOPER_ADDRESS=$(threefold_hubd keys show $KEYNAME --bech=val --keyring-backend test | grep -i address | cut -d ":" -f 2)
  while :
  do
    if threefold_hubd query staking validator $VALOPER_ADDRESS &> /dev/null; then
      echo "Validator Created"
      break
    else
      sleep 60
      threefold_hubd tx staking create-validator \
      --amount="$STAKE_AMOUNT" \
      --pubkey="$(threefold_hubd tendermint show-validator)" \
      --moniker="$MONIKER" \
      --chain-id="$CHAIN_ID" \
      --commission-rate="0.10" \
      --commission-max-rate="0.20" \
      --commission-max-change-rate="0.01" \
      --min-self-delegation="100" \
      --gas="auto" \
      --from=$KEYNAME \
      --keyring-backend="test" \
      --gas-prices $GAS_PRICES \
      --gas-adjustment $GAS_ADJUSTMENT \
      --yes
   fi
  done
  '
oneshot: true
after:
  - threefold_chain
