name: Build docker image

on:
  release:
    types: [published]
  workflow_dispatch:

  
jobs:

    build-docker:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        - uses: docker/build-push-action@v2
          with:
            context: docker/validator
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/tf-hub:latest
            push: true
        - name: Convert Docker image to flist
          run: |
            curl -f -X POST  -H "Authorization: bearer ${{secrets.ZEROHUB_TOKEN}}" ${{ secrets.ZEROHUB_URL }}/api/flist/me/docker -F 'image=${{ secrets.DOCKERHUB_USERNAME }}/tf-hub:latest'                                                                                                                                                                       
